# Generated by Django 4.2.6 on 2023-11-28 04:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Segmento',
            fields=[
                ('nombre', models.CharField(default='', max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('nombre', models.CharField(default='', max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioSegmento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segmento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CER3.segmento')),
                ('usuarios', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('fecha_inicio', models.DateField()),
                ('fecha_termino', models.DateField()),
                ('titulo', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('segmento', models.ManyToManyField(to='CER3.segmento')),
                ('tipo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='CER3.tipo')),
            ],
        ),
    ]
