# Generated by Django 4.2.6 on 2023-11-25 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Segmento',
            fields=[
                ('nombre', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('nombre', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('segmento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CER3.segmento')),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('fecha_inicio', models.DateField()),
                ('fecha_termino', models.DateField()),
                ('titulo', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('segmento', models.ManyToManyField(to='CER3.segmento')),
            ],
        ),
    ]
