# Generated by Django 4.2.5 on 2023-11-28 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CER3', '0002_alter_tipo_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='hit',
            field=models.IntegerField(default=0),
        ),
    ]
